CREATE TABLE status_flight (
    FlightNumber VARCHAR(50) PRIMARY KEY,
    DepartureDate DATE NOT NULL,
    DepartureAirportCode VARCHAR(10) NOT NULL,
    ScheduledDepartureLocalTime DATETIME NOT NULL,
    ActualDepartureLocalTime DATETIME,
    DepartureTerminal VARCHAR(50),
    DepartureGate VARCHAR(50),
    ArrivalAirportCode VARCHAR(10) NOT NULL,
    ScheduledArrivalLocalTime DATETIME NOT NULL,
    ActualArrivalLocalTime DATETIME,
    ArrivalTerminal VARCHAR(50),
    ArrivalGate VARCHAR(50),
    TimeStatusCode VARCHAR(10),
    TimeStatusDefinition VARCHAR(255),
    MarketingAirlineID VARCHAR(10) NOT NULL,
    MarketingFlightNumber VARCHAR(50) NOT NULL,
    AircraftCode VARCHAR(10) NOT NULL,
    AircraftRegistration VARCHAR(50),
    FlightStatusCode VARCHAR(10),
    FlightStatusDefinition VARCHAR(255),
    FOREIGN KEY (DepartureAirportCode) REFERENCES airport(AirportCode),
    FOREIGN KEY (ArrivalAirportCode) REFERENCES airport(AirportCode),
    FOREIGN KEY (MarketingAirlineID) REFERENCES airline(AirlineID),
    FOREIGN KEY (AircraftCode) REFERENCES aircraft(AircraftCode)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;